#!/bin/bash

su --command "greenbone-nvt-sync >> /var/log/gvm/greenbone-feed-sync.log" gvm
su --command "greenbone-feed-sync --type GVMD_DATA >>/var/log/gvm/greenbone-feed-sync.log" gvm
su --command "greenbone-feed-sync --type SCAP >> /var/log/gvm/greenbone-feed-sync.log" gvm
su --command "greenbone-feed-sync --type CERT >> /var/log/gvm/greenbone-feed-sync.log" gvm
openvas --update-vt-info
