#!/bin/bash

su --command "greenbone-nvt-sync >> /usr/local/var/log/gvm/greenbone-feed-sync.log" gvm
openvas --update-vt-info
su --command "greenbone-feed-sync --type GVMD_DATA >> /usr/local/var/log/gvm/greenbone-feed-sync.log" gvm
su --command "greenbone-feed-sync --type SCAP >> /usr/local/var/log/gvm/greenbone-feed-sync.log" gvm
su --command "greenbone-feed-sync --type CERT >> /usr/local/var/log/gvm/greenbone-feed-sync.log" gvm
